# Generated by Django 2.2.2 on 2022-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
