# Generated by Django 2.2.2 on 2022-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220926_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='update_interval',
            field=models.CharField(blank=True, default=5, max_length=10, null=True),
        ),
    ]
