# Generated by Django 2.2.2 on 2022-09-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_urls_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='status_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
