# Generated by Django 2.2.2 on 2022-09-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_urls_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='update_interval',
            field=models.CharField(blank=True, choices=[('Every 5 min', '5'), ('Every 10 min', '10'), ('Every 15 min', '15')], default=5, max_length=10, null=True),
        ),
    ]
