# Generated by Django 2.2.2 on 2022-09-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220928_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='status_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
